name: Nitro Deploy
description: Nitro Deploy speeds server.
author: productdevbook <hi@productdevbook.com>

branding:
  color: orange
  icon: cloud-lightning

inputs:
  nitro_deploy_token:
    required: true
    description: The Nitro Deploy token to use to authenticate with the Nitro Deploy API.
  nitro_deploy_export_folder:
    required: false
    default: .output
    description: The folder to export to Nitro Deploy. Defaults to the current working directory.
  nitro_deploy_build_command:
    required: false
    default: npm run build
    description: The command to run to build your project. Defaults to `npm run build`.

runs:
  using: node20
  main: dist/index.js
